module.exports = {
	"wi-wu-chanceflurries": "SnowWind",
	"wi-wu-chancerain": "Rain",
	"wi-wu-chancesleat": "Sleet",
	"wi-wu-chancesnow": "Snow",
	"wi-wu-chancetstorms": "Thunderstorm",
	"wi-wu-clear": "DaySunny",
	"wi-wu-cloudy": "DayCloudy",
	"wi-wu-flurries": "SnowWind",
	"wi-wu-hazy": "DayHaze",
	"wi-wu-mostlycloudy": "DayCloudy",
	"wi-wu-mostlysunny": "DaySunny",
	"wi-wu-partlycloudy": "DayCloudy",
	"wi-wu-partlysunny": "DaySunny",
	"wi-wu-rain": "Showers",
	"wi-wu-sleat": "Sleet",
	"wi-wu-snow": "Snow",
	"wi-wu-sunny": "DaySunny",
	"wi-wu-tstorms": "Thunderstorm",
	"wi-wu-unknown": "DaySunny"
};
