import React, { Component } from "react";
import * as Icons from "react-weather-icons";

export default class App extends Component {
	render() {
		let bgColor = "#FFF",
			color = "#000",
			size = 40;
		return (
			<div style={{ background: bgColor }}>
				<Icons.HurricaneWarning color={color} size={size} />
				<Icons.Time3 color={color} size={size} />
				<Icons.WindBeaufort6 color={color} size={size} />
				<Icons.MoonWaxingCrescent4 color={color} size={size} />
				<Icons.NightCloudyWindy color={color} size={size} />
				<Icons.NightAltHail color={color} size={size} />
				<Icons.Thermometer color={color} size={size} />
				<Icons.Time9 color={color} size={size} />
				<Icons.DayCloudyGusts color={color} size={size} />
				<Icons.NightClear color={color} size={size} />
				<Icons.Sunrise color={color} size={size} />
				<Icons.WindBeaufort9 color={color} size={size} />
				<Icons.MoonAltFirstQuarter color={color} size={size} />
				<Icons.DirectionLeft color={color} size={size} />
				<Icons.NightAltRainMix color={color} size={size} />
				<Icons.Sandstorm color={color} size={size} />
				<Icons.Horizon color={color} size={size} />
				<Icons.MoonWaningGibbous2 color={color} size={size} />
				<Icons.WindBeaufort1 color={color} size={size} />
				<Icons.NightAltThunderstorm color={color} size={size} />
				<Icons.MoonWaningGibbous1 color={color} size={size} />
				<Icons.WindBeaufort7 color={color} size={size} />
				<Icons.DayHaze color={color} size={size} />
				<Icons.Refresh color={color} size={size} />
				<Icons.MoonAltWaningGibbous6 color={color} size={size} />
				<Icons.NightAltSnow color={color} size={size} />
				<Icons.RainWind color={color} size={size} />
				<Icons.Hail color={color} size={size} />
				<Icons.StormShowers color={color} size={size} />
				<Icons.MoonAltWaxingCrescent6 color={color} size={size} />
				<Icons.NightSleetStorm color={color} size={size} />
				<Icons.NightAltSnowWind color={color} size={size} />
				<Icons.MoonWaningGibbous5 color={color} size={size} />
				<Icons.SmallCraftAdvisory color={color} size={size} />
				<Icons.DirectionRight color={color} size={size} />
				<Icons.Time6 color={color} size={size} />
				<Icons.NightStormShowers color={color} size={size} />
				<Icons.DaySprinkle color={color} size={size} />
				<Icons.NightLightning color={color} size={size} />
				<Icons.MoonAltWaningCrescent2 color={color} size={size} />
				<Icons.NightSprinkle color={color} size={size} />
				<Icons.Raindrop color={color} size={size} />
				<Icons.MoonAltWaxingGibbous2 color={color} size={size} />
				<Icons.MoonWaxingGibbous5 color={color} size={size} />
				<Icons.DirectionDownLeft color={color} size={size} />
				<Icons.NightAltRainWind color={color} size={size} />
				<Icons.CloudyWindy color={color} size={size} />
				<Icons.MoonWaningCrescent2 color={color} size={size} />
				<Icons.Na color={color} size={size} />
				<Icons.MoonWaningCrescent1 color={color} size={size} />
				<Icons.WindBeaufort8 color={color} size={size} />
				<Icons.MoonAltWaningCrescent1 color={color} size={size} />
				<Icons.CloudDown color={color} size={size} />
				<Icons.RainMix color={color} size={size} />
				<Icons.Volcano color={color} size={size} />
				<Icons.MoonFirstQuarter color={color} size={size} />
				<Icons.Raindrops color={color} size={size} />
				<Icons.DaySunnyOvercast color={color} size={size} />
				<Icons.MoonWaxingCrescent5 color={color} size={size} />
				<Icons.NightAltCloudyHigh color={color} size={size} />
				<Icons.DayLightning color={color} size={size} />
				<Icons.DayShowers color={color} size={size} />
				<Icons.NightSnowWind color={color} size={size} />
				<Icons.WindBeaufort3 color={color} size={size} />
				<Icons.Rain color={color} size={size} />
				<Icons.Time10 color={color} size={size} />
				<Icons.MoonAltThirdQuarter color={color} size={size} />
				<Icons.MoonWaxingCrescent6 color={color} size={size} />
				<Icons.MoonAltWaxingCrescent2 color={color} size={size} />
				<Icons.NightCloudy color={color} size={size} />
				<Icons.CloudyGusts color={color} size={size} />
				<Icons.Fog color={color} size={size} />
				<Icons.MoonWaningGibbous3 color={color} size={size} />
				<Icons.NightSleet color={color} size={size} />
				<Icons.MoonWaxingGibbous3 color={color} size={size} />
				<Icons.Umbrella color={color} size={size} />
				<Icons.Degrees color={color} size={size} />
				<Icons.WindBeaufort0 color={color} size={size} />
				<Icons.CloudRefresh color={color} size={size} />
				<Icons.Fire color={color} size={size} />
				<Icons.MoonWaxingCrescent1 color={color} size={size} />
				<Icons.NightAltSleet color={color} size={size} />
				<Icons.Moonrise color={color} size={size} />
				<Icons.NightAltSprinkle color={color} size={size} />
				<Icons.Time12 color={color} size={size} />
				<Icons.DayThunderstorm color={color} size={size} />
				<Icons.MoonAltWaningGibbous5 color={color} size={size} />
				<Icons.DayCloudyHigh color={color} size={size} />
				<Icons.DaySunny color={color} size={size} />
				<Icons.NightAltRain color={color} size={size} />
				<Icons.NightCloudyHigh color={color} size={size} />
				<Icons.MoonWaningGibbous4 color={color} size={size} />
				<Icons.DaySnow color={color} size={size} />
				<Icons.DaySnowThunderstorm color={color} size={size} />
				<Icons.Cloudy color={color} size={size} />
				<Icons.MoonAltFull color={color} size={size} />
				<Icons.Train color={color} size={size} />
				<Icons.Tsunami color={color} size={size} />
				<Icons.DayCloudyWindy color={color} size={size} />
				<Icons.GaleWarning color={color} size={size} />
				<Icons.CloudUp color={color} size={size} />
				<Icons.NightCloudyGusts color={color} size={size} />
				<Icons.WindBeaufort4 color={color} size={size} />
				<Icons.Flood color={color} size={size} />
				<Icons.DirectionDownRight color={color} size={size} />
				<Icons.DayRainMix color={color} size={size} />
				<Icons.NightRain color={color} size={size} />
				<Icons.WindBeaufort2 color={color} size={size} />
				<Icons.NightRainWind color={color} size={size} />
				<Icons.MoonWaxingGibbous1 color={color} size={size} />
				<Icons.NightHail color={color} size={size} />
				<Icons.MoonAltWaningGibbous1 color={color} size={size} />
				<Icons.WindDeg color={color} size={size} />
				<Icons.ThermometerExterior color={color} size={size} />
				<Icons.DayLightWind color={color} size={size} />
				<Icons.MoonAltWaxingGibbous4 color={color} size={size} />
				<Icons.NightAltShowers color={color} size={size} />
				<Icons.MoonAltWaningCrescent6 color={color} size={size} />
				<Icons.Time1 color={color} size={size} />
				<Icons.Showers color={color} size={size} />
				<Icons.NightPartlyCloudy color={color} size={size} />
				<Icons.Alien color={color} size={size} />
				<Icons.WindBeaufort5 color={color} size={size} />
				<Icons.MoonWaningCrescent5 color={color} size={size} />
				<Icons.Sleet color={color} size={size} />
				<Icons.MoonWaxingGibbous4 color={color} size={size} />
				<Icons.WindBeaufort11 color={color} size={size} />
				<Icons.Celsius color={color} size={size} />
				<Icons.MoonFull color={color} size={size} />
				<Icons.Smog color={color} size={size} />
				<Icons.NightAltLightning color={color} size={size} />
				<Icons.NightAltCloudyWindy color={color} size={size} />
				<Icons.Snow color={color} size={size} />
				<Icons.Hot color={color} size={size} />
				<Icons.HorizonAlt color={color} size={size} />
				<Icons.MoonAltWaxingCrescent3 color={color} size={size} />
				<Icons.RefreshAlt color={color} size={size} />
				<Icons.DirectionDown color={color} size={size} />
				<Icons.Tornado color={color} size={size} />
				<Icons.Barometer color={color} size={size} />
				<Icons.MoonAltWaningGibbous2 color={color} size={size} />
				<Icons.MoonNew color={color} size={size} />
				<Icons.SnowflakeCold color={color} size={size} />
				<Icons.MoonWaxingCrescent3 color={color} size={size} />
				<Icons.Time11 color={color} size={size} />
				<Icons.NightAltStormShowers color={color} size={size} />
				<Icons.MoonWaningCrescent4 color={color} size={size} />
				<Icons.DirectionUpLeft color={color} size={size} />
				<Icons.DirectionUp color={color} size={size} />
				<Icons.SolarEclipse color={color} size={size} />
				<Icons.Time4 color={color} size={size} />
				<Icons.WindBeaufort10 color={color} size={size} />
				<Icons.Time7 color={color} size={size} />
				<Icons.NightSnow color={color} size={size} />
				<Icons.MoonAltWaxingGibbous3 color={color} size={size} />
				<Icons.DaySnowWind color={color} size={size} />
				<Icons.MoonAltWaxingGibbous5 color={color} size={size} />
				<Icons.Earthquake color={color} size={size} />
				<Icons.MoonWaxingGibbous6 color={color} size={size} />
				<Icons.MoonWaxingGibbous2 color={color} size={size} />
				<Icons.NightFog color={color} size={size} />
				<Icons.Moonset color={color} size={size} />
				<Icons.Fahrenheit color={color} size={size} />
				<Icons.Cloud color={color} size={size} />
				<Icons.DaySleetStorm color={color} size={size} />
				<Icons.Hurricane color={color} size={size} />
				<Icons.Lightning color={color} size={size} />
				<Icons.StormWarning color={color} size={size} />
				<Icons.Humidity color={color} size={size} />
				<Icons.MoonThirdQuarter color={color} size={size} />
				<Icons.DayRainWind color={color} size={size} />
				<Icons.MoonAltWaxingCrescent4 color={color} size={size} />
				<Icons.MoonAltWaxingGibbous1 color={color} size={size} />
				<Icons.WindBeaufort12 color={color} size={size} />
				<Icons.StrongWind color={color} size={size} />
				<Icons.ThermometerInternal color={color} size={size} />
				<Icons.Stars color={color} size={size} />
				<Icons.DayRain color={color} size={size} />
				<Icons.DayWindy color={color} size={size} />
				<Icons.MoonAltWaxingCrescent5 color={color} size={size} />
				<Icons.NightShowers color={color} size={size} />
				<Icons.NightAltCloudy color={color} size={size} />
				<Icons.NightAltCloudyGusts color={color} size={size} />
				<Icons.SnowWind color={color} size={size} />
				<Icons.DirectionUpRight color={color} size={size} />
				<Icons.Windy color={color} size={size} />
				<Icons.NightAltSnowThunderstorm color={color} size={size} />
				<Icons.DayStormShowers color={color} size={size} />
				<Icons.Time5 color={color} size={size} />
				<Icons.MoonAltWaningCrescent3 color={color} size={size} />
				<Icons.LunarEclipse color={color} size={size} />
				<Icons.DayFog color={color} size={size} />
				<Icons.Time8 color={color} size={size} />
				<Icons.Dust color={color} size={size} />
				<Icons.MoonWaningCrescent3 color={color} size={size} />
				<Icons.NightAltSleetStorm color={color} size={size} />
				<Icons.Sprinkle color={color} size={size} />
				<Icons.Thunderstorm color={color} size={size} />
				<Icons.MoonAltNew color={color} size={size} />
				<Icons.MoonAltWaxingCrescent1 color={color} size={size} />
				<Icons.Smoke color={color} size={size} />
				<Icons.DaySleet color={color} size={size} />
				<Icons.MoonAltWaningGibbous4 color={color} size={size} />
				<Icons.MoonWaningGibbous6 color={color} size={size} />
				<Icons.MoonAltWaningGibbous3 color={color} size={size} />
				<Icons.Meteor color={color} size={size} />
				<Icons.NightAltPartlyCloudy color={color} size={size} />
				<Icons.Time2 color={color} size={size} />
				<Icons.DayHail color={color} size={size} />
				<Icons.DayCloudy color={color} size={size} />
				<Icons.NightRainMix color={color} size={size} />
				<Icons.NightThunderstorm color={color} size={size} />
				<Icons.MoonWaxingCrescent2 color={color} size={size} />
				<Icons.MoonAltWaxingGibbous6 color={color} size={size} />
				<Icons.MoonAltWaningCrescent5 color={color} size={size} />
				<Icons.MoonWaningCrescent6 color={color} size={size} />
				<Icons.NightSnowThunderstorm color={color} size={size} />
				<Icons.MoonAltWaningCrescent4 color={color} size={size} />
				<Icons.Sunset color={color} size={size} />
			</div>
		);
	}
}
